name: trabalho entre jobs

on:
  push:
    branch:
      - main

jobs:
  job-1:
    name: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - name: exibir versão do sistema operacional
        run: cat /etc/os-release  

      - name: criando arquivo message.txt
        run: echo "Estou realizando o treinamento "Github Actions" da LinuxTips" > ${{ github.workspace }}/message.txt
      
      - name: upload message file 
        uses: actions/upload-artifact@v4
        with:
          name: messages-upload
          path: ${{ github.workspace }}/message.txt

  job-2:
    name: download-artifac
    runs-on: ubuntu-latest
    depends_on: job-1 
    steps:
      - name: listando conteudo antes do download artifacs
        run: ls -lha

      - name: download message file 
        uses: actions/download-artifact@v4
        with:
          name: messages-upload
          path: messages

      - name: listando conteudo depois do download artifacs
        run: ls -lha && ls -lha /messages

      - name: recuperando arquivo e removendo repositorio
        run: cp messages/message.txt . && rm -rf /messages

      - name: listando repositório após recuperação do arquivo
        run: ls -lha

      - name: exibindo conteúdo do arquivo message
        run: cat message.txt