name: valid docker images

on:
  workflow_dispatch:
    inputs:
      validDockerImages:
        description: Insert Docker Image
        required: true
        default: nginx:latest
        type: string

jobs:
  valid-docker-images:
    name: valid Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Extraindo Imagem do Docker Registry
        run: |
          docker image pull ${{ github.event.inputs.validDockerImages }}

      - name: Validando Imagem a Ser Analisada pelo Scout
        run: |
          DOCKER_IMAGE=$(echo "${{ github.event.inputs.validDockerImages }}" | cut -d ':' -f 1)
          docker image ls | grep $DOCKER_IMAGE

      - name: Escaneando Imagem ${{ github.event.inputs.validDockerImages }}
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations,sbom
          image: ${{ github.event.inputs.validDockerImages }}
          dockerhub-user: ${{ vars.DOCKERHUB_USER }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}