name: valid docker images

on:
  workflow_dispatch:
    inputs:
      validDockerImages:
        description: Valid Docker Images
        required: false
        default: nginx:latest
        type: string

jobs:
  valid-docker-images:
    name: valid Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: extraindo imagem do Docker registry
        run: |
          docker image pull ${{ github.event.inputs.validDockerImages }}

      - name: validando imagem a ser analisada pelo scout
        run: |
          DOCKER_IMAGE=$(echo "${{ github.event.inputs.validDockerImages }}" | cut -d ':' -f 1)
          docker image ls | grep DOCKER_IMAGE

      - name: escaneando imagem ${{ github.event.inputs.validDockerImages }}
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations,sbom
          image: ${{ github.event.inputs.validDockerImages }}